In [69]:
import numpy as np
np.set_printoptions(threshold=np.nan)
import pandas as pd
import matplotlib.pyplot as plt
import scipy as sp

# Numpy

In [30]:
a = np.array([0,1,2,3,4,5])
print a.shape, a.ndim
a

(6,) 1


array([0, 1, 2, 3, 4, 5])

In [31]:
b = a.reshape((3,2)) # will create link, so changes in b produce changes to a
print b.shape, b.ndim
b

(3, 2) 2


array([[0, 1],
       [2, 3],
       [4, 5]])

In [34]:
b[1][0] = 77
a

array([ 0,  1, 77,  3,  4,  5])

In [36]:
c = a.reshape((3,2)).copy() # explicitly create object copy
c[1][0] = 101
print c, a

[[  0   1]
 [101   3]
 [  4   5]] [ 0  1 77  3  4  5]


In [39]:
c ** 2

array([[    0,     1],
       [10201,     9],
       [   16,    25]])

In [44]:
print a > 4, ' & ', a[a > 4]

[False False  True False False  True]  &  [77  5]


In [49]:
a.clip(0, 4) # from min to max if value > max value will be replaced with max value

array([0, 1, 4, 3, 4, 4])

Compare numpy with usual python stuff

In [51]:
import timeit
normal_py_sec = timeit.timeit('sum(x*x for x in range(1000))', number=10000)
naive_np_sec = timeit.timeit('sum(na*na)', setup="import numpy as np; na=np.arange(1000)", number=10000)
good_np_sec = timeit.timeit('na.dot(na)', setup="import numpy as np; na=np.arange(1000)", number=10000)

print "Normal Python: %f sec" % normal_py_sec
print "Naive NumPy: %f sec" % naive_np_sec
print "Good NumPy: %f sec" % good_np_sec

Normal Python: 0.792109 sec
Naive NumPy: 0.932891 sec
Good NumPy: 0.017122 sec


# SciPy

In [53]:
scipy.dot is np.dot # all numpy stuff available from scipy namespace

True

In [77]:
data = sp.genfromtxt("BuildingMachineLearningSystemsWithPython/ch01/data/web_traffic.tsv", delimiter="\t")
print "Shape is:", data.shape
print data[:3]

Shape is: (743, 2)
[[  1.00000000e+00   2.27200000e+03]
 [  2.00000000e+00              nan]
 [  3.00000000e+00   1.38600000e+03]]
